"""Production input registration, object verification and mutation locking."""

from __future__ import annotations

import hashlib
import re
import unicodedata
from dataclasses import dataclass
from io import BytesIO
from pathlib import Path

import openpyxl
import xlrd
from sqlalchemy import or_, select
from sqlalchemy.exc import IntegrityError
from sqlalchemy.orm import Session

from app.modules.files.interface import (
    MIN_DWG_SIZE_BYTES,
    StoredFile,
    get_storage_backend,
    validate_dwg_header,
)
from app.modules.jobs.interface import Job, cancel_job
from app.modules.workflows.models import WorkflowInputBatch, WorkflowInputItem, WorkflowRun
from app.platform.config.constants import EXCEL_FILE_EXTENSIONS
from app.platform.config.settings import settings
from app.platform.http.exceptions import AppHTTPException
from app.platform.storage.base import StorageError, StorageObjectNotFound

_WHITESPACE = re.compile(r"\s+")
ACTIVE_INPUT_JOB_STATUSES = {
    "pending",
    "queued",
    "running",
    "validating",
    "waiting_cad_worker",
}


@dataclass(frozen=True)
class FrozenInputReference:
    """Immutable deletion-guard projection without leaking workflow ORM rows."""

    workflow_id: int
    input_batch_id: int


def classify_human_input_extension(file_ext: str) -> str:
    """Map the only accepted human input extensions to immutable ledger roles."""
    normalized = file_ext.lower()
    if normalized == ".dxf":
        raise AppHTTPException(
            422,
            "INPUT_DXF_NOT_ALLOWED",
            "DXF must be generated by the server from a registered DWG input.",
        )
    if normalized == ".dwg":
        return "source_dwg"
    if normalized in EXCEL_FILE_EXTENSIONS:
        return "source_excel"
    raise AppHTTPException(
        422,
        "INPUT_FILE_TYPE_NOT_ALLOWED",
        "Production input accepts DWG files and exactly one Excel file.",
    )


def normalize_input_stem(name: str) -> str:
    basename = Path(name.replace("\\", "/")).name
    stem = basename.rsplit(".", 1)[0] if "." in basename else basename
    normalized = unicodedata.normalize("NFKC", stem).strip()
    return _WHITESPACE.sub(" ", normalized).casefold()


def create_input_batch(
    db: Session,
    workflow: WorkflowRun,
    *,
    created_by: int,
) -> WorkflowInputBatch:
    if workflow.workflow_type != "linux_production":
        raise AppHTTPException(
            422,
            "INPUT_BATCH_WORKFLOW_TYPE_INVALID",
            "Input batches are only available for linux_production workflows.",
        )
    existing = db.scalar(
        select(WorkflowInputBatch).where(WorkflowInputBatch.workflow_run_id == workflow.id)
    )
    if existing is not None:
        return existing
    try:
        with db.begin_nested():
            batch = WorkflowInputBatch(
                workflow=workflow,
                project_id=workflow.project_id,
                created_by=created_by,
                status="uploading",
                version=1,
            )
            db.add(batch)
            db.flush()
    except IntegrityError:
        winner = db.scalar(
            select(WorkflowInputBatch)
            .where(WorkflowInputBatch.workflow_run_id == workflow.id)
            .with_for_update()
        )
        if winner is None:
            raise
        return winner
    return batch


def lock_input_batch(db: Session, batch: WorkflowInputBatch) -> WorkflowInputBatch:
    """Serialize mutable input operations and refresh their item collection."""
    locked = db.scalar(
        select(WorkflowInputBatch).where(WorkflowInputBatch.id == batch.id).with_for_update()
    )
    if locked is None:
        raise AppHTTPException(404, "INPUT_BATCH_NOT_FOUND", "Input batch not found.")
    db.expire(locked, ["items"])
    return locked


def read_verified_input_object(stored: StoredFile) -> bytes:
    """Read one registered object while rechecking its immutable SQL ledger."""
    if stored.status == "deleted":
        raise AppHTTPException(404, "INPUT_FILE_NOT_FOUND", "Input file is unavailable.")
    storage = get_storage_backend()
    digest = hashlib.sha256()
    payload = bytearray()
    maximum = settings.max_upload_size_mb * 1024 * 1024
    try:
        for chunk in storage.iter_file(stored.bucket, stored.storage_key):
            payload.extend(chunk)
            if len(payload) > maximum:
                raise AppHTTPException(
                    413,
                    "INPUT_OBJECT_TOO_LARGE",
                    "Input object exceeds the configured upload limit.",
                )
            digest.update(chunk)
    except AppHTTPException:
        raise
    except StorageObjectNotFound as exc:
        raise AppHTTPException(
            409,
            "INPUT_OBJECT_MISSING",
            "The registered input object is missing from storage.",
        ) from exc
    except StorageError as exc:
        raise AppHTTPException(
            503,
            "INPUT_OBJECT_READ_FAILED",
            "The input object could not be read from storage.",
        ) from exc
    if len(payload) != stored.size_bytes:
        raise AppHTTPException(
            409,
            "INPUT_OBJECT_SIZE_MISMATCH",
            "The input object size does not match its file registration.",
        )
    if digest.hexdigest() != stored.sha256:
        raise AppHTTPException(
            409,
            "INPUT_OBJECT_CHECKSUM_MISMATCH",
            "The input object checksum does not match its file registration.",
        )
    return bytes(payload)


def validate_dwg_payload(payload: bytes) -> None:
    validate_dwg_header(payload[:6])
    if len(payload) < MIN_DWG_SIZE_BYTES:
        raise AppHTTPException(
            415,
            "FILE_NOT_DWG",
            f"File too small ({len(payload)} bytes) — legitimate DWG files exceed {MIN_DWG_SIZE_BYTES} bytes.",
        )


def validate_excel_payload(file_ext: str, payload: bytes) -> None:
    try:
        if file_ext == ".xlsx":
            workbook = openpyxl.load_workbook(BytesIO(payload), read_only=True, data_only=True)
            try:
                visible_count = sum(
                    1 for sheet in workbook.worksheets if sheet.sheet_state == "visible"
                )
            finally:
                workbook.close()
        else:
            workbook = xlrd.open_workbook(file_contents=payload, on_demand=True)
            try:
                visible_count = sum(
                    1 for sheet in workbook.sheets() if getattr(sheet, "visibility", 0) == 0
                )
            finally:
                workbook.release_resources()
    except Exception as exc:
        raise AppHTTPException(
            415,
            "INPUT_EXCEL_UNREADABLE",
            "The Excel file is damaged, encrypted, or does not match its extension.",
        ) from exc
    if visible_count < 1:
        raise AppHTTPException(
            415,
            "INPUT_EXCEL_NO_VISIBLE_SHEET",
            "The Excel file must contain at least one visible worksheet.",
        )


def register_input_file(
    db: Session,
    batch: WorkflowInputBatch,
    stored: StoredFile,
) -> WorkflowInputItem:
    batch = lock_input_batch(db, batch)
    if batch.status == "frozen":
        raise AppHTTPException(
            409, "INPUT_BATCH_FROZEN", "Frozen input batches cannot be modified."
        )
    existing = next((item for item in batch.items if item.file_id == stored.id), None)
    if existing is not None:
        return existing
    file_ext = stored.file_ext.lower()
    role = classify_human_input_extension(file_ext)
    if role == "source_excel" and any(item.role == "source_excel" for item in batch.items):
        raise AppHTTPException(
            409,
            "INPUT_EXCEL_ALREADY_EXISTS",
            "The input batch already contains an Excel file. Remove it before replacement.",
        )
    payload = read_verified_input_object(stored)
    if role == "source_dwg":
        validate_dwg_payload(payload)
    else:
        validate_excel_payload(file_ext, payload)
    item = WorkflowInputItem(
        batch=batch,
        file_id=stored.id,
        role=role,
        original_name=stored.original_name,
        normalized_stem=normalize_input_stem(stored.original_name),
        status="uploaded",
    )
    db.add(item)
    db.flush()
    return item


def get_input_batch(db: Session, workflow_id: int) -> WorkflowInputBatch:
    batch = db.scalar(
        select(WorkflowInputBatch).where(WorkflowInputBatch.workflow_run_id == workflow_id)
    )
    if batch is None:
        raise AppHTTPException(404, "INPUT_BATCH_NOT_FOUND", "Input batch not found.")
    return batch


def remove_input_item(
    db: Session,
    batch: WorkflowInputBatch,
    item_id: int,
) -> None:
    batch = lock_input_batch(db, batch)
    if batch.status == "frozen":
        raise AppHTTPException(
            409, "INPUT_BATCH_FROZEN", "Frozen input batches cannot be modified."
        )
    item = next((value for value in batch.items if value.id == item_id), None)
    if item is None:
        raise AppHTTPException(404, "INPUT_ITEM_NOT_FOUND", "Input item not found.")
    if item.conversion_job_id is not None:
        job = db.get(Job, item.conversion_job_id)
        if job is not None and job.status in ACTIVE_INPUT_JOB_STATUSES:
            cancel_job(db, job)
    db.delete(item)
    db.flush()
    batch.status = "uploading"
    batch.error_code = None
    batch.error_message = None


def find_frozen_input_reference(
    db: Session,
    file_id: int,
    *,
    for_update: bool = False,
) -> FrozenInputReference | None:
    """Return only the frozen-manifest identifiers needed by file deletion guards."""
    stmt = (
        select(WorkflowInputBatch)
        .join(
            WorkflowInputItem,
            WorkflowInputItem.input_batch_id == WorkflowInputBatch.id,
        )
        .where(
            WorkflowInputBatch.status == "frozen",
            or_(
                WorkflowInputItem.file_id == file_id,
                WorkflowInputItem.derived_dxf_file_id == file_id,
            ),
        )
        .limit(1)
    )
    if for_update:
        stmt = stmt.with_for_update()
    batch = db.scalar(stmt)
    if batch is None:
        return None
    return FrozenInputReference(
        workflow_id=batch.workflow_run_id,
        input_batch_id=batch.id,
    )
