"""add excel_final tables

Revision ID: 3480bd86ddc3
Revises: 1d1696c7e854
Create Date: 2026-07-10 15:17:43.575420
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '3480bd86ddc3'
down_revision: str | None = '1d1696c7e854'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('excel_final_batches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.String(length=32), nullable=False, comment='init_table / tekla_tsv'),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('component_count', sa.Integer(), nullable=False),
    sa.Column('part_count', sa.Integer(), nullable=False),
    sa.Column('total_net_weight', sa.Float(), nullable=True),
    sa.Column('total_gross_weight', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_excel_final_batches_job_id'), 'excel_final_batches', ['job_id'], unique=False)
    op.create_table('excel_final_components',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('component_no', sa.String(length=128), nullable=True),
    sa.Column('component_qty', sa.Integer(), nullable=True),
    sa.Column('total_weight', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['excel_final_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_excel_final_components_batch_id'), 'excel_final_components', ['batch_id'], unique=False)
    op.create_table('excel_final_parts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('component_no', sa.String(length=128), nullable=True),
    sa.Column('component_qty', sa.Integer(), nullable=True),
    sa.Column('part_type', sa.String(length=64), nullable=True),
    sa.Column('part_no', sa.String(length=128), nullable=True),
    sa.Column('profile_spec', sa.String(length=128), nullable=True),
    sa.Column('spec', sa.String(length=64), nullable=True),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('left_inset', sa.Float(), nullable=True),
    sa.Column('right_inset', sa.Float(), nullable=True),
    sa.Column('cut_length', sa.Float(), nullable=True),
    sa.Column('material', sa.String(length=64), nullable=True),
    sa.Column('qty', sa.Float(), nullable=True),
    sa.Column('total_qty', sa.Float(), nullable=True),
    sa.Column('total_length', sa.Float(), nullable=True),
    sa.Column('density', sa.Float(), nullable=True),
    sa.Column('theo_unit_weight', sa.Float(), nullable=True),
    sa.Column('theo_total_weight', sa.Float(), nullable=True),
    sa.Column('net_unit_weight', sa.Float(), nullable=True),
    sa.Column('net_total_weight', sa.Float(), nullable=True),
    sa.Column('table_net_weight', sa.Float(), nullable=True),
    sa.Column('gross_unit_weight', sa.Float(), nullable=True),
    sa.Column('gross_total_weight', sa.Float(), nullable=True),
    sa.Column('table_gross_weight', sa.Float(), nullable=True),
    sa.Column('surface_area', sa.Float(), nullable=True),
    sa.Column('total_surface_area', sa.Float(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['excel_final_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_excel_final_parts_batch_id'), 'excel_final_parts', ['batch_id'], unique=False)
    op.create_index(op.f('ix_excel_final_parts_material'), 'excel_final_parts', ['material'], unique=False)
    op.create_index(op.f('ix_excel_final_parts_part_no'), 'excel_final_parts', ['part_no'], unique=False)
    # Celery/Kombu SQL transport tables are created lazily by the Celery worker
    # at first task dispatch and may not exist on a fresh deploy where no worker
    # has run yet. MySQL cannot roll back DDL, so a failed DROP leaves the new
    # tables created above in place and a retry would fail with "already exists".
    # Use IF EXISTS on every DROP so the migration is idempotent.
    op.execute("DROP TABLE IF EXISTS celery_tasksetmeta")
    op.execute("DROP TABLE IF EXISTS kombu_message")
    op.execute("DROP TABLE IF EXISTS kombu_queue")
    op.execute("DROP TABLE IF EXISTS celery_taskmeta")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TABLE IF NOT EXISTS celery_taskmeta ("
               "id INTEGER NOT NULL AUTO_INCREMENT, task_id VARCHAR(155), "
               "status VARCHAR(50), result BLOB, date_done DATETIME, "
               "traceback TEXT, name VARCHAR(155), args BLOB, kwargs BLOB, "
               "worker VARCHAR(155), retries INTEGER, queue VARCHAR(155), "
               "PRIMARY KEY (id))")
    op.execute("CREATE TABLE IF NOT EXISTS kombu_queue ("
               "id INTEGER NOT NULL AUTO_INCREMENT, name VARCHAR(200), "
               "PRIMARY KEY (id))")
    op.execute("CREATE TABLE IF NOT EXISTS kombu_message ("
               "id INTEGER NOT NULL AUTO_INCREMENT, visible TINYINT(1), "
               "timestamp DATETIME, payload TEXT NOT NULL, "
               "version SMALLINT NOT NULL, queue_id INTEGER, "
               "PRIMARY KEY (id))")
    op.execute("CREATE TABLE IF NOT EXISTS celery_tasksetmeta ("
               "id INTEGER NOT NULL AUTO_INCREMENT, taskset_id VARCHAR(155), "
               "result BLOB, date_done DATETIME, PRIMARY KEY (id))")
    op.drop_index(op.f('ix_excel_final_parts_part_no'), table_name='excel_final_parts')
    op.drop_index(op.f('ix_excel_final_parts_material'), table_name='excel_final_parts')
    op.drop_index(op.f('ix_excel_final_parts_batch_id'), table_name='excel_final_parts')
    op.drop_table('excel_final_parts')
    op.drop_index(op.f('ix_excel_final_components_batch_id'), table_name='excel_final_components')
    op.drop_table('excel_final_components')
    op.drop_index(op.f('ix_excel_final_batches_job_id'), table_name='excel_final_batches')
    op.drop_table('excel_final_batches')
    # ### end Alembic commands ###
