"""add excel_final tables

Revision ID: 3480bd86ddc3
Revises: 1d1696c7e854
Create Date: 2026-07-10 15:17:43.575420
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3480bd86ddc3'
down_revision: str | None = '1d1696c7e854'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('excel_final_batches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.String(length=32), nullable=False, comment='init_table / tekla_tsv'),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('component_count', sa.Integer(), nullable=False),
    sa.Column('part_count', sa.Integer(), nullable=False),
    sa.Column('total_net_weight', sa.Float(), nullable=True),
    sa.Column('total_gross_weight', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_excel_final_batches_job_id'), 'excel_final_batches', ['job_id'], unique=False)
    op.create_table('excel_final_components',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('component_no', sa.String(length=128), nullable=True),
    sa.Column('component_qty', sa.Integer(), nullable=True),
    sa.Column('total_weight', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['excel_final_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_excel_final_components_batch_id'), 'excel_final_components', ['batch_id'], unique=False)
    op.create_table('excel_final_parts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('component_no', sa.String(length=128), nullable=True),
    sa.Column('component_qty', sa.Integer(), nullable=True),
    sa.Column('part_type', sa.String(length=64), nullable=True),
    sa.Column('part_no', sa.String(length=128), nullable=True),
    sa.Column('profile_spec', sa.String(length=128), nullable=True),
    sa.Column('spec', sa.String(length=64), nullable=True),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('left_inset', sa.Float(), nullable=True),
    sa.Column('right_inset', sa.Float(), nullable=True),
    sa.Column('cut_length', sa.Float(), nullable=True),
    sa.Column('material', sa.String(length=64), nullable=True),
    sa.Column('qty', sa.Float(), nullable=True),
    sa.Column('total_qty', sa.Float(), nullable=True),
    sa.Column('total_length', sa.Float(), nullable=True),
    sa.Column('density', sa.Float(), nullable=True),
    sa.Column('theo_unit_weight', sa.Float(), nullable=True),
    sa.Column('theo_total_weight', sa.Float(), nullable=True),
    sa.Column('net_unit_weight', sa.Float(), nullable=True),
    sa.Column('net_total_weight', sa.Float(), nullable=True),
    sa.Column('table_net_weight', sa.Float(), nullable=True),
    sa.Column('gross_unit_weight', sa.Float(), nullable=True),
    sa.Column('gross_total_weight', sa.Float(), nullable=True),
    sa.Column('table_gross_weight', sa.Float(), nullable=True),
    sa.Column('surface_area', sa.Float(), nullable=True),
    sa.Column('total_surface_area', sa.Float(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['excel_final_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_excel_final_parts_batch_id'), 'excel_final_parts', ['batch_id'], unique=False)
    op.create_index(op.f('ix_excel_final_parts_material'), 'excel_final_parts', ['material'], unique=False)
    op.create_index(op.f('ix_excel_final_parts_part_no'), 'excel_final_parts', ['part_no'], unique=False)
    op.drop_index(op.f('ix_celery_tasksetmeta_date_done'), table_name='celery_tasksetmeta')
    op.drop_index(op.f('taskset_id'), table_name='celery_tasksetmeta')
    op.drop_table('celery_tasksetmeta')
    op.drop_index(op.f('name'), table_name='kombu_queue')
    op.drop_table('kombu_queue')
    op.drop_index(op.f('ix_kombu_message_timestamp'), table_name='kombu_message')
    op.drop_index(op.f('ix_kombu_message_timestamp_id'), table_name='kombu_message')
    op.drop_index(op.f('ix_kombu_message_visible'), table_name='kombu_message')
    op.drop_table('kombu_message')
    op.drop_index(op.f('ix_celery_taskmeta_date_done'), table_name='celery_taskmeta')
    op.drop_index(op.f('task_id'), table_name='celery_taskmeta')
    op.drop_table('celery_taskmeta')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('celery_taskmeta',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('task_id', mysql.VARCHAR(length=155), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('result', sa.BLOB(), nullable=True),
    sa.Column('date_done', mysql.DATETIME(), nullable=True),
    sa.Column('traceback', mysql.TEXT(), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=155), nullable=True),
    sa.Column('args', sa.BLOB(), nullable=True),
    sa.Column('kwargs', sa.BLOB(), nullable=True),
    sa.Column('worker', mysql.VARCHAR(length=155), nullable=True),
    sa.Column('retries', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('queue', mysql.VARCHAR(length=155), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('task_id'), 'celery_taskmeta', ['task_id'], unique=True)
    op.create_index(op.f('ix_celery_taskmeta_date_done'), 'celery_taskmeta', ['date_done'], unique=False)
    op.create_table('kombu_message',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('visible', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.Column('payload', mysql.TEXT(), nullable=False),
    sa.Column('version', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=False),
    sa.Column('queue_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['queue_id'], ['kombu_queue.id'], name=op.f('FK_kombu_message_queue')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_kombu_message_visible'), 'kombu_message', ['visible'], unique=False)
    op.create_index(op.f('ix_kombu_message_timestamp_id'), 'kombu_message', ['timestamp', 'id'], unique=False)
    op.create_index(op.f('ix_kombu_message_timestamp'), 'kombu_message', ['timestamp'], unique=False)
    op.create_table('kombu_queue',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('name'), 'kombu_queue', ['name'], unique=True)
    op.create_table('celery_tasksetmeta',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('taskset_id', mysql.VARCHAR(length=155), nullable=True),
    sa.Column('result', sa.BLOB(), nullable=True),
    sa.Column('date_done', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('taskset_id'), 'celery_tasksetmeta', ['taskset_id'], unique=True)
    op.create_index(op.f('ix_celery_tasksetmeta_date_done'), 'celery_tasksetmeta', ['date_done'], unique=False)
    op.drop_index(op.f('ix_excel_final_parts_part_no'), table_name='excel_final_parts')
    op.drop_index(op.f('ix_excel_final_parts_material'), table_name='excel_final_parts')
    op.drop_index(op.f('ix_excel_final_parts_batch_id'), table_name='excel_final_parts')
    op.drop_table('excel_final_parts')
    op.drop_index(op.f('ix_excel_final_components_batch_id'), table_name='excel_final_components')
    op.drop_table('excel_final_components')
    op.drop_index(op.f('ix_excel_final_batches_job_id'), table_name='excel_final_batches')
    op.drop_table('excel_final_batches')
    # ### end Alembic commands ###
