"""add_batch_name_to_files

Revision ID: 53cd59adf848
Revises: c3d2e1f0a9b8
Create Date: 2026-07-06 15:11:09.362621
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '53cd59adf848'
down_revision: str | None = 'c3d2e1f0a9b8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('batch_name', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_files_batch_name'), 'files', ['batch_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_files_batch_name'), table_name='files')
    op.drop_column('files', 'batch_name')
    # ### end Alembic commands ###
